#!/bin/bash

cd "$GITHUB_WORKSPACE" || exit 1

export GITHUB_TOKEN="${INPUT_GITHUB_TOKEN}"

echo "MYSQL_HOST: ${MYSQL_HOST}"
echo "MYSQL_PORT: ${MYSQL_PORT}"
echo "MYSQL_USER: ${MYSQL_USER}"
echo "MYSQL_PASSWORD: ${MYSQL_PASSWORD}"
echo "MYSQL_DATABASE: ${MYSQL_DATABASE}"
echo "SCHEMA_PATH: ${SCHEMA_PATH}"

# ex) mysqldef -h 127.0.0.1 -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < schema/schema.sql
mysqldef -h ${MYSQL_HOST} -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -P ${MYSQL_PORT} ${MYSQL_DATABASE} < ${SCHEMA_PATH}
